Better example bot
cygni/paintbot-client-js pull request #12
Opened 2021-04-08 19:23 UTC by juiceit

2021-04-08 19:32 UTC, rickardenglund approved these changes

2021-04-09 14:19 UTC, maxdavidson requested changes

2021-04-09 14:19 UTC, maxdavidson commented on bot/bot.js
> +var currentDirection = 0;
Don't use var
```suggestion
let currentDirection = 0;
```

2021-04-09 14:19 UTC, maxdavidson commented on bot/bot.js
> +var currentDirection = 0;
You should reset the bot state between games, check the comment in the onMessage handler

2021-04-09 14:21 UTC, maxdavidson commented on bot/bot.js
> +var currentDirection = 0;
You could also create a bot class and use a new instance for each game

2021-04-20 04:50 UTC, merged